//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by client-gen/saf1u. DO NOT EDIT.

// Code generated by lister-gen. DO NOT EDIT.

package v1

// HausListerExpansion allows custom methods to be added to
// HausLister.
type HausListerExpansion interface{}

// HausNamespaceListerExpansion allows custom methods to be added to
// HausNamespaceLister.
type HausNamespaceListerExpansion interface{}
