apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: hauses.haus.com  # name of the CRD
spec:
  group: haus.com             # custom API group
  names:
    plural: hauses          # plural name for the resource
    singular: haus         # singular name
    kind: Haus             # kind of the custom resource
    shortNames:
    - hs                         # short name for quick access
  scope: Namespaced              # namespaced or cluster scope
  versions:
    - name: v1
      served: true               # CRD can be used
      storage: true              # this version is the primary storage
      schema:                    # OpenAPI v3 schema validation
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                count:
                  type: integer
                  minimum: 1
                  maximum: 10
                replicas:
                  type: integer
                location:
                  type: string
            status:                           # Define the status schema
              type: object
              properties:
                state:
                  type: string
      additionalPrinterColumns: #(optional)
        - name: count
          type: integer
          jsonPath: .spec.count
      subresources:
        status: {}
        scale:
          specReplicasPath: .spec.replicas
          statusReplicasPath: .status.replicas
