//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by client-gen/saf1u. DO NOT EDIT.

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/saf1u/haus.com/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Hauses returns a HausInformer.
	Hauses() HausInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Hauses returns a HausInformer.
func (v *version) Hauses() HausInformer {
	return &hausInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
