//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by client-gen/saf1u. DO NOT EDIT.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	hauscomv1 "github.com/saf1u/haus.com/pkg/apis/haus.com/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHauses implements HausInterface
type FakeHauses struct {
	Fake *FakeSamplecontrollerV1
	ns   string
}

var hausesResource = schema.GroupVersionResource{Group: "samplecontroller.k8s.io", Version: "v1", Resource: "hauses"}

var hausesKind = schema.GroupVersionKind{Group: "samplecontroller.k8s.io", Version: "v1", Kind: "Haus"}

// Get takes name of the haus, and returns the corresponding haus object, and an error if there is any.
func (c *FakeHauses) Get(ctx context.Context, name string, options v1.GetOptions) (result *hauscomv1.Haus, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(hausesResource, c.ns, name), &hauscomv1.Haus{})

	if obj == nil {
		return nil, err
	}
	return obj.(*hauscomv1.Haus), err
}

// List takes label and field selectors, and returns the list of Hauses that match those selectors.
func (c *FakeHauses) List(ctx context.Context, opts v1.ListOptions) (result *hauscomv1.HausList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(hausesResource, hausesKind, c.ns, opts), &hauscomv1.HausList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &hauscomv1.HausList{ListMeta: obj.(*hauscomv1.HausList).ListMeta}
	for _, item := range obj.(*hauscomv1.HausList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested hauses.
func (c *FakeHauses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(hausesResource, c.ns, opts))

}

// Create takes the representation of a haus and creates it.  Returns the server's representation of the haus, and an error, if there is any.
func (c *FakeHauses) Create(ctx context.Context, haus *hauscomv1.Haus, opts v1.CreateOptions) (result *hauscomv1.Haus, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(hausesResource, c.ns, haus), &hauscomv1.Haus{})

	if obj == nil {
		return nil, err
	}
	return obj.(*hauscomv1.Haus), err
}

// Update takes the representation of a haus and updates it. Returns the server's representation of the haus, and an error, if there is any.
func (c *FakeHauses) Update(ctx context.Context, haus *hauscomv1.Haus, opts v1.UpdateOptions) (result *hauscomv1.Haus, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(hausesResource, c.ns, haus), &hauscomv1.Haus{})

	if obj == nil {
		return nil, err
	}
	return obj.(*hauscomv1.Haus), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeHauses) UpdateStatus(ctx context.Context, haus *hauscomv1.Haus, opts v1.UpdateOptions) (*hauscomv1.Haus, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(hausesResource, "status", c.ns, haus), &hauscomv1.Haus{})

	if obj == nil {
		return nil, err
	}
	return obj.(*hauscomv1.Haus), err
}

// Delete takes name of the haus and deletes it. Returns an error if one occurs.
func (c *FakeHauses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(hausesResource, c.ns, name, opts), &hauscomv1.Haus{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHauses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(hausesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &hauscomv1.HausList{})
	return err
}

// Patch applies the patch and returns the patched haus.
func (c *FakeHauses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *hauscomv1.Haus, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(hausesResource, c.ns, name, pt, data, subresources...), &hauscomv1.Haus{})

	if obj == nil {
		return nil, err
	}
	return obj.(*hauscomv1.Haus), err
}
