//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by client-gen/saf1u. DO NOT EDIT.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/saf1u/haus.com/pkg/client/clientset/versioned/typed/haus.com/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeSamplecontrollerV1 struct {
	*testing.Fake
}

func (c *FakeSamplecontrollerV1) Hauses(namespace string) v1.HausInterface {
	return &FakeHauses{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeSamplecontrollerV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
