//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by client-gen/saf1u. DO NOT EDIT.

// Code generated by client-gen. DO NOT EDIT.

package v1

type HausExpansion interface{}
